#!/data/data/com.termux/files/usr/bin/bash

# Dependencies - peerflix, binutils, git, nodejs, fzf

clear

mkdir -p "$HOME"/.cache/mattflix

menu="fzf"
baseurl="https://1337x.to"
cachedir="$HOME/.cache/mattflix"

pages="3"

if [ -z "$1" ]; then
  clear
  url="$baseurl/home/"
else
  query=$(printf '%s' "$*" | tr ' ' '+' )
  url="$baseurl/search/$query/1/"
fi

curl -s "$url" > "$cachedir"/tmp.html

sed -i '/Popular Music Torrents/,$d' "$cachedir"/tmp.html

if [ "$1" ]; then
for ((i=2;i<="$pages";i++)) do curl -s "$baseurl/search/$query/$i/" >> "$cachedir"/tmp.html; done
fi

grep -o '/torrent/.*' "$cachedir"/tmp.html |
  sed 's/<[^>]*>//g;s|/| |g' | awk '{print $3}' > "$cachedir"/titles.bw

result_count=$(grep -c '.*' "$cachedir"/titles.bw)
if [ "$result_count" -lt 1 ]; then
  echo "No Result found. Try again"
  exit 0
fi

if [ -z "$1" ]; then

rm "$cachedir"/{tmp2.html,seedleech.bw,size.bw,seedleech.bw} 2>/dev/null

grep -E '/torrent/' "$cachedir"/tmp.html | sed -E 's#.*(/torrent/.*)/">.*/#\1#;s/td>//g' |
  sed -n '/>/p' | sed 's/>//g' > "$cachedir"/links2.bw

hlines=$(cat "$cachedir"/links2.bw)

for i in $hlines; do curl -s "${baseurl}${i}/" >> "$cachedir"/tmp2.html; done

grep -o '<span class="seeds.*</span>\|<span class="leeches.*</span>' "$cachedir"/tmp2.html |
  sed 's/<[^>]*>//g' | sed 'N;s/\n/ /' > "$cachedir"/seedleech.bw

grep -o 'size</strong>.*' "$cachedir"/tmp2.html | sed 's/<span class="seeds">.*<\/span>//g' |
  sed -e 's/<[^>]*>//g' | awk '{print $2, $3}' > "$cachedir"/size.bw

grep -o '<td class="coll-2 seeds.*</td>\|<td class="coll-3 leeches.*</td>' "$cachedir"/tmp.html |
  sed 's/<[^>]*>//g' | sed 'N;s/\n/ /' >> "$cachedir"/seedleech.bw

grep -o '<td class="coll-4 size.*</td>' "$cachedir"/tmp.html |
  sed 's/<span class="seeds">.*<\/span>//g' |
  sed -e 's/<[^>]*>//g' >> "$cachedir"/size.bw

else

grep -o '<td class="coll-2 seeds.*</td>\|<td class="coll-3 leeches.*</td>' "$cachedir"/tmp.html |
  sed 's/<[^>]*>//g' | sed 'N;s/\n/ /' > "$cachedir"/seedleech.bw

grep -o '<td class="coll-4 size.*</td>' "$cachedir"/tmp.html |
  sed 's/<span class="seeds">.*<\/span>//g' |
  sed -e 's/<[^>]*>//g' > "$cachedir"/size.bw

fi

grep -E '/torrent/' "$cachedir"/tmp.html |
  sed -E 's#.*(/torrent/.*)/">.*/#\1#' |
  sed 's/td>//g;s/>//g' > "$cachedir"/links.bw

sed 's/\./ /g; s/\-/ /g' "$cachedir"/titles.bw |
  sed 's/[^A-Za-z0-9 ]//g' | tr -s " " > "$cachedir"/tmp && mv "$cachedir"/tmp "$cachedir"/titles.bw

awk '{print NR " - ["$0"]"}' "$cachedir"/size.bw > "$cachedir"/tmp && mv "$cachedir"/tmp "$cachedir"/size.bw

awk '{print "[S:"$1 " L:"$2"]" }' "$cachedir"/seedleech.bw > "$cachedir"/tmp && mv "$cachedir"/tmp "$cachedir"/seedleech.bw

LINE="$(paste -d\  "$cachedir"/{size.bw,seedleech.bw,titles.bw} |
  $menu |
  cut -d\- -f1 |
  awk '{$1=$1; print}')"

if [ -z "$LINE" ]; then
  echo "No Result selected. Exiting..."
  exit 0
fi

clear

echo "Searching Magnet seeds"
url=$(head -n $LINE "$cachedir"/links.bw | tail -n +$LINE)
fullURL="${baseurl}${url}/"

curl -s "$fullURL" > "$cachedir"/tmp.html
magnet=$(grep -o "magnet.*" "$cachedir"/tmp.html | cut -d'"' -f1 | head -n 1)

trap "rm -rf $TMPDIR/torrent-stream/*" EXIT

peerflix "$magnet" --mpv -a --no-quit
